window.addEventListener("load", function(){
    $("#plan1").click(function(){
        $(this).toggleClass("seleccionado");
    $("#plan2").removeClass("seleccionado");
    $("#plan3").removeClass("seleccionado");
    $("#plan4").removeClass("seleccionado");
        $("#planSeleccionado").val("landingPage");
    });
    $("#plan2").click(function(){
        $(this).toggleClass("seleccionado");
    $("#plan1").removeClass("seleccionado");
    $("#plan3").removeClass("seleccionado");
    $("#plan4").removeClass("seleccionado");
        $("#planSeleccionado").val("fullPage");
    });
    $("#plan3").click(function(){
        $(this).toggleClass("seleccionado");
    $("#plan2").removeClass("seleccionado");
    $("#plan1").removeClass("seleccionado");
    $("#plan4").removeClass("seleccionado");
        $("#planSeleccionado").val("eCommerce");
    });
    $("#plan4").click(function(){
        $(this).toggleClass("seleccionado");
    $("#plan2").removeClass("seleccionado");
    $("#plan3").removeClass("seleccionado");
    $("#plan1").removeClass("seleccionado");
        $("#planSeleccionado").val("custom");
    });
    
    $("#landingService").click(function(){
        $("#plan1").toggleClass("seleccionado");
        $("#plan2").removeClass("seleccionado");
        $("#plan3").removeClass("seleccionado");
        $("#plan4").removeClass("seleccionado");
        $("#planSeleccionado").val("landingPage");
    });
    $("#fullService").click(function(){
        $("#plan2").toggleClass("seleccionado");
        $("#plan1").removeClass("seleccionado");
        $("#plan3").removeClass("seleccionado");
        $("#plan4").removeClass("seleccionado");
        $("#planSeleccionado").val("fullPage");
    });
    $("#ecommerceService").click(function(){
        $("#plan3").toggleClass("seleccionado");
        $("#plan2").removeClass("seleccionado");
        $("#plan1").removeClass("seleccionado");
        $("#plan4").removeClass("seleccionado");
        $("#planSeleccionado").val("eCommerce");
    });
    $("#customService").click(function(){
        $("#plan4").toggleClass("seleccionado");
        $("#plan2").removeClass("seleccionado");
        $("#plan3").removeClass("seleccionado");
        $("#plan1").removeClass("seleccionado");
        $("#planSeleccionado").val("custom");
    });
});